name: riverpod_graph
description: A CLI tool to generate provider dependency graphs for Riverpod apps.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^6.3.0
  path: ^1.9.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

executables:
  riverpod_graph: bin/riverpod_graph.dart
