name: riverpod_graph
description: A CLI tool to generate provider dependency graphs for Riverpod apps.
version: 1.0.3
homepage: https://github.com/yourusername/riverpod_graph

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^7.4.5
  path: ^1.9.1

dev_dependencies:
  lints: 5.1.1
  test: ^1.24.0

executables:
  riverpod_graph: riverpod_graph
